version: '3'
services:
 web:
  container_name: build
  image: "debasis4/devbaseimage"
  ports:
  - "8080:8080"
  volumes:
  - ./sanity:/var/log/debasis
  restart: always
  depends_on:
    - redis
 redis:
  container_name: devdb
  image: "redis:alpine"
  ports:
  - "6379:6379"
